import { Product } from './types';

export const PRODUCTS: Product[] = [
  // ========== JEWELRY ==========
  {
    id: 'j001',
    name: 'Rosette Pearl Choker',
    nameUrdu: 'روزیٹ موتی ہار',
    price: 599,
    originalPrice: 799,
    category: 'Jewelry',
    subcategory: 'Chokers',
    description: 'Delicate freshwater pearl choker with a gold rosette charm. Perfect for everyday elegance or a special occasion.',
    descriptionUrdu: 'نازک سیپی موتی کا ہار جس میں سونے کی گلاب کی تصویر ہے۔ روزانہ کی خوبصورتی یا خاص موقع کے لیے بہترین۔',
    images: [
      'https://images.pexels.com/photos/1630344/pexels-photo-1630344.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2697787/pexels-photo-2697787.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Freshwater Pearl, Gold-Plated Brass',
    dimensions: '14-16 inch adjustable',
    customizable: false,
    tags: ['choker', 'pearl', 'elegant', 'gold'],
    weight: '12g',
  },
  {
    id: 'j002',
    name: 'Cherry Blossom Ring Set',
    nameUrdu: 'چیری بلاسم انگوٹھیاں',
    price: 449,
    originalPrice: 599,
    category: 'Jewelry',
    subcategory: 'Rings',
    description: 'Set of 3 dainty stackable rings with cherry blossom motifs. Rose gold plated with crystal accents.',
    descriptionUrdu: 'تین نازک قابل انباشت انگوٹھیوں کا سیٹ جن میں چیری بلاسم کے نمونے ہیں۔',
    images: [
      'https://images.pexels.com/photos/2697787/pexels-photo-2697787.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1630344/pexels-photo-1630344.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Rose Gold Plated Brass, Cubic Zirconia',
    dimensions: 'Sizes 6-8 available',
    customizable: true,
    tags: ['rings', 'rose gold', 'stackable', 'cute'],
    weight: '8g',
  },
  {
    id: 'j003',
    name: 'Gold Twisted Knot Earrings',
    nameUrdu: 'گولڈ ٹوئسٹڈ ناٹ بالیاں',
    price: 349,
    category: 'Jewelry',
    subcategory: 'Earrings',
    description: 'Luxe matte gold twisted knot stud earrings. Minimalist yet statement-making — perfect for everyday glam.',
    descriptionUrdu: 'خوبصورت میٹ گولڈ ٹوئسٹڈ ناٹ اسٹڈ بالیاں۔ سادہ مگر خاص — روزمرہ گلیمر کے لیے بہترین۔',
    images: [
      '/ffffffffffffffffffffffffffffff.PNG',
      'https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.7,
    reviewCount: 56,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    material: 'Matte Gold Plated Brass',
    dimensions: '2cm diameter',
    customizable: false,
    tags: ['earrings', 'gold', 'twisted', 'minimalist', 'stud'],
    weight: '6g',
  },
  {
    id: 'j004',
    name: 'Minimalist Heart Bracelet',
    nameUrdu: 'سادہ دل کڑا',
    price: 299,
    originalPrice: 399,
    category: 'Jewelry',
    subcategory: 'Bracelets',
    description: 'Dainty gold chain bracelet with a tiny heart charm. Adjustable length, perfect layering piece.',
    descriptionUrdu: 'نازک سونے کی زنجیر کا کڑا چھوٹے دل کے ساتھ۔ قابل ایڈجسٹ لمبائی۔',
    images: [
      'https://images.pexels.com/photos/2735970/pexels-photo-2735970.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 201,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: '14K Gold-Filled Chain',
    dimensions: '6-7.5 inch adjustable',
    customizable: false,
    tags: ['bracelet', 'heart', 'gold', 'minimalist'],
    weight: '6g',
  },
  {
    id: 'j005',
    name: 'Open Heart Pendant Necklace',
    nameUrdu: 'اوپن ہارٹ پنڈنٹ نیکلس',
    price: 699,
    category: 'Jewelry',
    subcategory: 'Necklaces',
    description: 'Delicate silver open heart pendant on a thin cord chain. Romantic minimalist style — comes as a set of 2.',
    descriptionUrdu: 'پتلی ڈوری زنجیر پر نازک چاندی کا اوپن ہارٹ پنڈنٹ۔ رومانوی سادہ انداز — 2 کا سیٹ۔',
    images: [
      '/fahhhhhhhhhhhhhh.PNG',
      'https://images.pexels.com/photos/2735970/pexels-photo-2735970.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviewCount: 43,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    material: 'Silver-Plated, Cord Chain',
    dimensions: 'Pendant: 2cm, Chain: 45cm',
    customizable: false,
    tags: ['necklace', 'heart', 'pendant', 'silver', 'romantic'],
    weight: '10g',
  },
  {
    id: 'j006',
    name: 'Crystal Hoop Earrings',
    nameUrdu: 'کرسٹل ہوپ بالیاں',
    price: 399,
    category: 'Jewelry',
    subcategory: 'Earrings',
    description: 'Elegant small crystal-studded hoop earrings. Versatile enough for school or a date.',
    descriptionUrdu: 'خوبصورت چھوٹی کرسٹل جڑی ہوپ بالیاں۔ اسکول یا ڈیٹ کے لیے بہترین۔',
    images: [
      'https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2697787/pexels-photo-2697787.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 79,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    material: 'Rose Gold Plated Brass, Crystal',
    dimensions: '2cm diameter',
    customizable: false,
    tags: ['earrings', 'hoops', 'crystal', 'elegant'],
    weight: '7g',
  },
  {
    id: 'j007',
    name: 'Name Initial Necklace',
    nameUrdu: 'نام کے ابتدائی حروف کا ہار',
    price: 799,
    originalPrice: 999,
    category: 'Jewelry',
    subcategory: 'Necklaces',
    description: 'Personalized gold-filled letter necklace with your initial. Makes the most meaningful gift.',
    descriptionUrdu: 'ذاتی سونے سے بھرے حرف کا ہار آپ کے ابتدائی حروف کے ساتھ۔ سب سے معنی خیز تحفہ۔',
    images: [
      'https://images.pexels.com/photos/2735970/pexels-photo-2735970.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1630344/pexels-photo-1630344.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 5.0,
    reviewCount: 312,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: '18K Gold-Filled',
    dimensions: 'Chain: 16-18 inch adjustable',
    customizable: true,
    tags: ['necklace', 'personalized', 'initial', 'gift'],
    weight: '8g',
  },

  // ========== HAIR ACCESSORIES ==========
  {
    id: 'h001',
    name: 'Satin Bow Hair Clip',
    nameUrdu: 'ساٹن بو بال کلپ',
    price: 199,
    originalPrice: 249,
    category: 'Hair Accessories',
    subcategory: 'Clips',
    description: 'Oversized satin bow clip in 6 gorgeous colors. Perfect for a soft girl aesthetic.',
    descriptionUrdu: 'بڑا ساٹن بو کلپ ۶ خوبصورت رنگوں میں۔ سافٹ گرل لُک کے لیے بہترین۔',
    images: [
      'https://images.pexels.com/photos/3189139/pexels-photo-3189139.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 445,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Satin Fabric, Metal Clip',
    dimensions: '10cm width',
    customizable: false,
    tags: ['hair clip', 'bow', 'satin', 'cute', 'soft girl'],
    weight: '15g',
  },
  {
    id: 'h002',
    name: 'Cherry Claw Clip Set',
    nameUrdu: 'چیری کلا کلپ سیٹ',
    price: 350,
    originalPrice: 450,
    category: 'Hair Accessories',
    subcategory: 'Claw Clips',
    description: 'Set of 3 cherry-shaped claw clips in red, pink, and cream. Adorable and functional.',
    descriptionUrdu: 'تین چیری کی شکل کے کلا کلپس کا سیٹ سرخ، گلابی اور کریم رنگ میں۔',
    images: [
      'https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3189139/pexels-photo-3189139.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 189,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Acrylic',
    dimensions: 'Small: 5cm, Medium: 7cm',
    customizable: false,
    tags: ['claw clip', 'cherry', 'set', 'cute'],
    weight: '30g',
  },
  {
    id: 'h003',
    name: 'Floral Pearl Headband',
    nameUrdu: 'پھول موتی ہیڈ بینڈ',
    price: 449,
    category: 'Hair Accessories',
    subcategory: 'Headbands',
    description: 'Elegant pearl and silk flower headband. Bridal-worthy yet perfect for everyday wear.',
    descriptionUrdu: 'خوبصورت موتی اور ریشمی پھول والا ہیڈ بینڈ۔ شادی کے قابل پھر بھی روزانہ پہننے کے لیے بہترین۔',
    images: [
      'https://images.pexels.com/photos/3189139/pexels-photo-3189139.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.7,
    reviewCount: 67,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    material: 'Pearl, Silk Flowers, Velvet Band',
    dimensions: 'One size fits all',
    customizable: false,
    tags: ['headband', 'pearl', 'floral', 'elegant'],
    weight: '45g',
  },
  {
    id: 'h004',
    name: 'Scrunchie Pack - Soft Girl',
    nameUrdu: 'سکرنچی پیک سافٹ گرل',
    price: 250,
    category: 'Hair Accessories',
    subcategory: 'Scrunchies',
    description: '5-pack of satin scrunchies in blush, cream, lavender, pink, and burgundy. Gentle on hair.',
    descriptionUrdu: '5 ساٹن سکرنچیز کا پیک بلش، کریم، لیونڈر، گلابی اور برگنڈی رنگوں میں۔',
    images: [
      'https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3189139/pexels-photo-3189139.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 521,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Satin, Elastic',
    dimensions: 'Standard size',
    customizable: false,
    tags: ['scrunchie', 'satin', 'pack', 'hair tie'],
    weight: '50g',
  },
  {
    id: 'h005',
    name: 'Rhinestone Bobby Pin Set',
    nameUrdu: 'رائن اسٹون بابی پن سیٹ',
    price: 299,
    originalPrice: 399,
    category: 'Hair Accessories',
    subcategory: 'Pins',
    description: 'Pack of 10 dazzling rhinestone bobby pins in gold and silver. Stack them for impact.',
    descriptionUrdu: '10 چمکتی ہوئی رائن اسٹون بابی پنز کا پیک سونے اور چاندی کے رنگ میں۔',
    images: [
      'https://images.pexels.com/photos/3189139/pexels-photo-3189139.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviewCount: 143,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    material: 'Metal, Rhinestone',
    dimensions: '6cm length',
    customizable: false,
    tags: ['bobby pin', 'rhinestone', 'glam', 'set'],
    weight: '20g',
  },
  {
    id: 'h006',
    name: 'Velvet Ribbon Hair Bow',
    nameUrdu: 'ویلویٹ ربن بال بو',
    price: 349,
    category: 'Hair Accessories',
    subcategory: 'Bows',
    description: 'Luxurious large velvet ribbon bow on a barrette. Coquette aesthetic made easy.',
    descriptionUrdu: 'بیرٹ پر خوبصورت بڑا ویلویٹ ربن بو۔ کوکیٹ لُک کو آسان بناتا ہے۔',
    images: [
      'https://images.pexels.com/photos/3065209/pexels-photo-3065209.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3189139/pexels-photo-3189139.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Velvet Ribbon, Metal Barrette',
    dimensions: '12cm width',
    customizable: false,
    tags: ['bow', 'velvet', 'coquette', 'barrette'],
    weight: '18g',
  },

  // ========== BOUQUETS & GIFTS ==========
  {
    id: 'bg001',
    name: 'Dried Rose Bouquet',
    nameUrdu: 'خشک گلاب کا گلدستہ',
    price: 1299,
    originalPrice: 1599,
    category: 'Bouquets & Gifts',
    subcategory: 'Bouquets',
    description: 'Beautifully arranged dried rose bouquet with pampas grass and baby breath. Lasts forever.',
    descriptionUrdu: 'خوبصورت سوکھے گلاب کا گلدستہ پیمپاس گراس اور بچے کی سانس کے ساتھ۔ ہمیشہ قائم رہتا ہے۔',
    images: [
      'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/931176/pexels-photo-931176.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 98,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Dried Roses, Pampas Grass, Baby Breath',
    dimensions: '30cm height',
    customizable: true,
    tags: ['bouquet', 'dried flowers', 'gift', 'romantic'],
    weight: '200g',
  },
  {
    id: 'bg002',
    name: 'Purple Dream Gift Set',
    nameUrdu: 'پرپل ڈریم گفٹ سیٹ',
    price: 1299,
    originalPrice: 1699,
    category: 'Bouquets & Gifts',
    subcategory: 'Gift Sets',
    description: 'Dreamy purple gift set: butterfly "Make a Wish" necklace, marble purple scrunchie, and crystal bead bracelet. Beautifully packaged.',
    descriptionUrdu: 'خوابناک پرپل گفٹ سیٹ: تتلی "میک اے وش" نیکلس، ماربل پرپل سکرنچی، اور کرسٹل بیڈ کڑا۔ خوبصورتی سے پیک کیا گیا۔',
    images: [
      '/g.PNG',
      'https://images.pexels.com/photos/1303084/pexels-photo-1303084.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 5.0,
    reviewCount: 67,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Mixed — Necklace, Scrunchie, Bracelet',
    customizable: true,
    tags: ['gift set', 'purple', 'butterfly', 'necklace', 'bracelet'],
    weight: '150g',
  },
  {
    id: 'bg003',
    name: 'Soap Rose Bouquet',
    nameUrdu: 'صابن گلاب کا گلدستہ',
    price: 899,
    originalPrice: 1199,
    category: 'Bouquets & Gifts',
    subcategory: 'Bouquets',
    description: 'Handcrafted soap roses arranged in a bouquet — beautiful, fragrant, and keeps a long time.',
    descriptionUrdu: 'ہاتھ سے بنے صابن گلاب گلدستے میں ترتیب دیے گئے — خوبصورت، خوشبودار اور لمبے عرصے تک قائم۔',
    images: [
      'https://images.pexels.com/photos/931176/pexels-photo-931176.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1303084/pexels-photo-1303084.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    material: 'Scented Soap, Wire, Ribbon',
    dimensions: '25cm height',
    customizable: true,
    tags: ['soap roses', 'bouquet', 'fragrant', 'gift'],
    weight: '350g',
  },
  {
    id: 'bg004',
    name: 'Personalized Jewelry Box',
    nameUrdu: 'ذاتی زیور بکس',
    price: 1499,
    category: 'Bouquets & Gifts',
    subcategory: 'Gift Boxes',
    description: 'Custom name-engraved velvet jewelry box in blush pink. Perfect gift for her.',
    descriptionUrdu: 'بلش پنک رنگ کا کسٹم نام نقاشی والا ویلویٹ جیولری بکس۔ اس کے لیے بہترین تحفہ۔',
    images: [
      'https://images.pexels.com/photos/1303084/pexels-photo-1303084.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 55,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    material: 'Velvet, Wood, Mirror Interior',
    dimensions: '15cm x 12cm x 8cm',
    customizable: true,
    tags: ['jewelry box', 'personalized', 'velvet', 'gift'],
    weight: '400g',
  },
  {
    id: 'bg005',
    name: 'Pink Candy Gloss Gift Box',
    nameUrdu: 'پنک کینڈی گلاس گفٹ باکس',
    price: 1799,
    originalPrice: 2199,
    category: 'Bouquets & Gifts',
    subcategory: 'Gift Boxes',
    description: 'Adorable pink gift box loaded with Nykaa Candy Gloss lip gloss, fluffy pink butterfly clip, pearl bubble hair clips, and a flower petal scrunchie. The perfect girly surprise.',
    descriptionUrdu: 'پیاری گلابی گفٹ باکس نیکا کینڈی گلاس لپ گلاس، فلفی گلابی تتلی کلپ، موتی بیبل بال کلپس، اور پھول پنکھڑی سکرنچی کے ساتھ۔ بہترین گرلی سرپرائز۔',
    images: [
      '/lll.PNG',
      'https://images.pexels.com/photos/1303084/pexels-photo-1303084.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 5.0,
    reviewCount: 89,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Mixed — Lip Gloss, Hair Accessories, Clips',
    customizable: true,
    tags: ['gift box', 'pink', 'lip gloss', 'hair clip', 'cute', 'birthday'],
    weight: '300g',
  },

  // ========== BEAUTY ==========
  {
    id: 'bty001',
    name: 'Rose Petal Lip Gloss',
    nameUrdu: 'گلاب پنکھڑی لپ گلاس',
    price: 350,
    originalPrice: 450,
    category: 'Beauty',
    subcategory: 'Lips',
    description: 'Hydrating rose-tinted lip gloss with a glossy finish. Non-sticky, long lasting.',
    descriptionUrdu: 'نمی دینے والا گلاب رنگ کا لپ گلاس چمکدار تکمیل کے ساتھ۔ نہ چپکنے والا، دیرپا۔',
    images: [
      'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3373738/pexels-photo-3373738.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Cruelty-free, Halal certified',
    customizable: false,
    tags: ['lip gloss', 'rose', 'hydrating', 'beauty'],
    weight: '10g',
  },
  {
    id: 'bty002',
    name: 'Cherry Blush Palette',
    nameUrdu: 'چیری بلش پیلیٹ',
    price: 749,
    originalPrice: 999,
    category: 'Beauty',
    subcategory: 'Face',
    description: '4-shade blush palette in cherry, coral, peach, and rose. Buildable pigment for a natural flush.',
    descriptionUrdu: '4 شیڈ بلش پیلیٹ چیری، کورل، آڑو اور گلاب میں۔ قدرتی رنگت کے لیے بلڈ ایبل پگمنٹ۔',
    images: [
      'https://images.pexels.com/photos/3373738/pexels-photo-3373738.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.7,
    reviewCount: 143,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Cruelty-free, Halal certified',
    customizable: false,
    tags: ['blush', 'palette', 'face', 'makeup'],
    weight: '25g',
  },
  {
    id: 'bty003',
    name: 'Glass Skin Serum Drops',
    nameUrdu: 'گلاس اسکن سیرم ڈراپس',
    price: 899,
    category: 'Beauty',
    subcategory: 'Skincare',
    description: 'K-beauty inspired glass skin serum with niacinamide and hyaluronic acid. Glow from within.',
    descriptionUrdu: 'نیاسینامائڈ اور ہائیلورونک ایسڈ کے ساتھ کے-بیوٹی سے متاثر گلاس اسکن سیرم۔',
    images: [
      'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3373738/pexels-photo-3373738.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 198,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Niacinamide, Hyaluronic Acid, Peptides',
    customizable: false,
    tags: ['serum', 'skincare', 'glass skin', 'glow'],
    weight: '30ml',
  },
  {
    id: 'bty004',
    name: 'Lash & Brow Growth Serum',
    nameUrdu: 'پلکیں اور بھویں بڑھانے کا سیرم',
    price: 650,
    originalPrice: 850,
    category: 'Beauty',
    subcategory: 'Eyes',
    description: 'Natural lash and brow growth serum with castor oil and biotin. See results in 4 weeks.',
    descriptionUrdu: 'قدرتی پلکوں اور بھوؤں کی نشوونما کا سیرم ارنڈی کے تیل اور بائیوٹن کے ساتھ۔',
    images: [
      'https://images.pexels.com/photos/3373738/pexels-photo-3373738.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviewCount: 312,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    material: 'Castor Oil, Biotin, Vitamin E',
    customizable: false,
    tags: ['lash', 'brow', 'growth', 'serum'],
    weight: '5ml',
  },
  {
    id: 'bty005',
    name: 'Satin Sleep Set',
    nameUrdu: 'ساٹن اسلیپ سیٹ',
    price: 799,
    category: 'Beauty',
    subcategory: 'Haircare',
    description: 'Pink satin pillowcase + sleep mask + scrunchie set. Protect your skin and hair while you sleep.',
    descriptionUrdu: 'گلابی ساٹن تکیے کا کور + اسلیپ ماسک + سکرنچی سیٹ۔ سوتے وقت اپنی جلد اور بالوں کی حفاظت کریں۔',
    images: [
      'https://images.pexels.com/photos/3373738/pexels-photo-3373738.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 187,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Satin',
    dimensions: 'Standard size',
    customizable: false,
    tags: ['satin', 'sleep', 'skincare', 'haircare'],
    weight: '200g',
  },

  // ========== PRESS-ON NAILS ==========
  {
    id: 'n001',
    name: 'French Tip Gel Nails',
    nameUrdu: 'فرنچ ٹپ جیل ناخن',
    price: 549,
    originalPrice: 699,
    category: 'Press-On Nails',
    subcategory: 'Classic',
    description: 'Salon-quality French tip press-on nails. Includes 24 nails in sizes XS to XL + glue.',
    descriptionUrdu: 'سیلون کوالٹی فرنچ ٹپ پریس آن ناخن۔ 24 ناخن XS سے XL سائز + گلو شامل ہے۔',
    images: [
      'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/939836/pexels-photo-939836.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 423,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'ABS Plastic, Gel Top Coat',
    dimensions: '24 nails, 12 sizes',
    customizable: false,
    tags: ['press-on', 'french tip', 'nails', 'classic'],
    weight: '15g',
  },
  {
    id: 'n002',
    name: 'Cherry Red Coffin Nails',
    nameUrdu: 'چیری ریڈ کوفن ناخن',
    price: 649,
    category: 'Press-On Nails',
    subcategory: 'Coffin',
    description: 'Bold cherry red long coffin nails with glossy finish. Make a statement.',
    descriptionUrdu: 'جرات مندانہ چیری ریڈ لمبے کوفن ناخن چمکدار تکمیل کے ساتھ۔',
    images: [
      'https://images.pexels.com/photos/939836/pexels-photo-939836.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 289,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'ABS Plastic, Gel Top Coat',
    dimensions: '24 nails, 12 sizes',
    customizable: false,
    tags: ['press-on', 'coffin', 'red', 'bold'],
    weight: '18g',
  },
  {
    id: 'n003',
    name: 'Floral 3D Nail Art Set',
    nameUrdu: 'پھول 3D نیل آرٹ سیٹ',
    price: 799,
    originalPrice: 999,
    category: 'Press-On Nails',
    subcategory: 'Nail Art',
    description: 'Short almond nails with hand-painted floral designs and pearl accents. Korean nail art style.',
    descriptionUrdu: 'ہاتھ سے پینٹ کیے گئے پھولوں کے ڈیزائن اور موتی کے لہجوں کے ساتھ چھوٹے بادام ناخن۔',
    images: [
      'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/939836/pexels-photo-939836.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    material: 'ABS Plastic, Gel, Pearl Embellishment',
    dimensions: '24 nails, 12 sizes',
    customizable: false,
    tags: ['press-on', 'floral', '3D', 'Korean nail art'],
    weight: '20g',
  },
  {
    id: 'n004',
    name: 'Romantic Cool Mauve Nails',
    nameUrdu: 'رومانٹک کول موو ناخن',
    price: 499,
    category: 'Press-On Nails',
    subcategory: 'Almond',
    description: '"Romantic Cool" mauve almond press-on nails — 12 pcs with glue tabs. Gorgeous dusty pink-mauve shade, medium length.',
    descriptionUrdu: '"رومانٹک کول" موو بادام پریس آن ناخن — 12 پیس گلو ٹیبز کے ساتھ۔ خوبصورت ڈسٹی پنک-موو شیڈ، درمیانی لمبائی۔',
    images: [
      '/real.PNG',
      'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'ABS Plastic, Gel Top Coat',
    dimensions: '12 nails, 6 sizes',
    customizable: false,
    tags: ['press-on', 'mauve', 'almond', 'romantic', 'aesthetic'],
    weight: '16g',
  },
  {
    id: 'n005',
    name: 'Nail Sticker Mega Pack',
    nameUrdu: 'نیل اسٹیکر میگا پیک',
    price: 350,
    originalPrice: 499,
    category: 'Press-On Nails',
    subcategory: 'Nail Stickers',
    description: '5-sheet mega pack of nail stickers: hearts, stars, flowers, butterflies, and Y2K designs.',
    descriptionUrdu: '5 شیٹ میگا پیک نیل اسٹیکرز: دل، ستارے، پھول، تتلیاں اور Y2K ڈیزائن۔',
    images: [
      'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/939836/pexels-photo-939836.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviewCount: 354,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    material: 'Vinyl, Self-adhesive',
    dimensions: '5 sheets, 200+ stickers',
    customizable: false,
    tags: ['nail stickers', 'pack', 'nail art', 'cute'],
    weight: '15g',
  },

  // ========== CUTE ACCESSORIES ==========
  {
    id: 'a001',
    name: 'Cherry Phone Charm',
    nameUrdu: 'چیری فون چارم',
    price: 249,
    originalPrice: 349,
    category: 'Cute Accessories',
    subcategory: 'Phone Accessories',
    description: 'Adorable beaded phone charm with cherry and heart motifs. Fits all phone cases with a strap hole.',
    descriptionUrdu: 'چیری اور دل کے نمونوں کے ساتھ پیارا موتیوں والا فون چارم۔',
    images: [
      'https://images.pexels.com/photos/5750980/pexels-photo-5750980.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 567,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Glass Beads, Polymer Clay',
    customizable: true,
    tags: ['phone charm', 'cherry', 'beaded', 'cute'],
    weight: '15g',
  },
  {
    id: 'a002',
    name: 'Aesthetic Sticker Pack',
    nameUrdu: 'ایستھیٹک اسٹیکر پیک',
    price: 199,
    category: 'Cute Accessories',
    subcategory: 'Stationery',
    description: '100+ holographic and matte stickers in cherry, coquette, and Y2K themes. Waterproof.',
    descriptionUrdu: '100+ ہولوگرافک اور میٹ اسٹیکرز چیری، کوکیٹ اور Y2K تھیمز میں۔ واٹر پروف۔',
    images: [
      'https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/5750980/pexels-photo-5750980.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 412,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Vinyl, Holographic Foil',
    customizable: false,
    tags: ['stickers', 'holographic', 'cute', 'waterproof'],
    weight: '30g',
  },
  {
    id: 'a003',
    name: 'Coquette Keychain',
    nameUrdu: 'کوکیٹ کی چین',
    price: 299,
    category: 'Cute Accessories',
    subcategory: 'Keychains',
    description: 'Plush cherry keychain with a mini bow. Attach to your bag for an instant coquette upgrade.',
    descriptionUrdu: 'منی بو کے ساتھ پلش چیری کی چین۔ فوری کوکیٹ اپگریڈ کے لیے بیگ سے لگائیں۔',
    images: [
      'https://images.pexels.com/photos/5750980/pexels-photo-5750980.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.9,
    reviewCount: 389,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    material: 'Plush, Metal Ring',
    customizable: false,
    tags: ['keychain', 'plush', 'cherry', 'coquette'],
    weight: '25g',
  },
  {
    id: 'a004',
    name: 'Mini Coin Purse',
    nameUrdu: 'منی سکہ پرس',
    price: 399,
    originalPrice: 499,
    category: 'Cute Accessories',
    subcategory: 'Bags',
    description: 'Kawaii cherry coin purse with zipper. PU leather, adorable gift for any age.',
    descriptionUrdu: 'زپ کے ساتھ کاواای چیری سکہ پرس۔ PU چمڑا، ہر عمر کے لیے پیارا تحفہ۔',
    images: [
      'https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/5750980/pexels-photo-5750980.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    material: 'PU Leather',
    dimensions: '10cm x 8cm',
    customizable: false,
    tags: ['coin purse', 'kawaii', 'cute', 'accessory'],
    weight: '60g',
  },
  {
    id: 'a005',
    name: 'Beaded Bag Charm Set',
    nameUrdu: 'موتی بیگ چارم سیٹ',
    price: 449,
    originalPrice: 549,
    category: 'Cute Accessories',
    subcategory: 'Bag Charms',
    description: 'Set of 3 handmade beaded bag charms in cherry, strawberry, and flower designs.',
    descriptionUrdu: 'چیری، اسٹرابیری اور پھول کے ڈیزائن میں 3 ہاتھ سے بنے موتیوں والے بیگ چارمز کا سیٹ۔',
    images: [
      'https://images.pexels.com/photos/5750980/pexels-photo-5750980.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.8,
    reviewCount: 223,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    material: 'Glass Beads, Metal Clasp',
    customizable: false,
    tags: ['bag charm', 'beaded', 'handmade', 'set'],
    weight: '40g',
  },
  {
    id: 'a006',
    name: 'Y2K Star Sunglasses',
    nameUrdu: 'Y2K اسٹار سن گلاسز',
    price: 599,
    category: 'Cute Accessories',
    subcategory: 'Eyewear',
    description: 'Retro Y2K star-shaped tinted sunglasses in pink, blue, and yellow. UV400 protection.',
    descriptionUrdu: 'ریٹرو Y2K ستارے کی شکل والے ٹنٹڈ سن گلاسز گلابی، نیلے اور پیلے رنگ میں۔ UV400 تحفظ۔',
    images: [
      'https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/5750980/pexels-photo-5750980.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviewCount: 178,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    material: 'Acrylic Frame, UV400 Lens',
    customizable: false,
    tags: ['sunglasses', 'Y2K', 'retro', 'aesthetic'],
    weight: '35g',
  },
];

export const getFeaturedProducts = () => PRODUCTS.filter(p => p.isFeatured);
export const getBestSellers = () => PRODUCTS.filter(p => p.isBestSeller);
export const getNewArrivals = () => PRODUCTS.filter(p => p.isNew);
export const getProductsByCategory = (category: string) =>
  PRODUCTS.filter(p => p.category === category);
export const getProductById = (id: string) =>
  PRODUCTS.find(p => p.id === id);
