import { Testimonial } from './types';

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'tst001',
    name: 'Zara Malik',
    city: 'Lahore',
    rating: 5,
    comment: 'The cherry phone charm is EVERYTHING. I get compliments on it literally every single day at uni. The quality is so much better than anything I\'ve found at local markets. Will 100% be ordering again!',
    date: '2026-04-15',
    productBought: 'Cherry Phone Charm',
    image: '',
  },
  {
    id: 'tst002',
    name: 'Aamna Siddiqui',
    city: 'Karachi',
    rating: 5,
    comment: 'Ordered the Birthday Gift Hamper for my bestie and she literally cried happy tears. The packaging was SO aesthetic and everything inside was perfect. Delivery was super fast too — came in 2 days!',
    date: '2026-03-28',
    productBought: 'Birthday Gift Hamper',
    image: '',
  },
  {
    id: 'tst003',
    name: 'Maryam Hassan',
    city: 'Islamabad',
    rating: 5,
    comment: 'The velvet ribbon bow is sooo cute omg. I wear it with literally every outfit now. The quality is amazing and it holds my hair so well. CherryCore is my new fav shop!',
    date: '2026-04-02',
    productBought: 'Velvet Ribbon Hair Bow',
    image: '',
  },
  {
    id: 'tst004',
    name: 'Fatima Baig',
    city: 'Faisalabad',
    rating: 5,
    comment: 'The Name Initial Necklace is absolutely gorgeous. I ordered one for myself and two as gifts and everyone loved them. Very good gold plating, hasn\'t tarnished at all after weeks of wearing!',
    date: '2026-04-20',
    productBought: 'Name Initial Necklace',
    image: '',
  },
  {
    id: 'tst005',
    name: 'Hira Qureshi',
    city: 'Rawalpindi',
    rating: 5,
    comment: 'The Cherry Red Coffin Nails are STUNNING. Lasted me a full week without any chips. The sizing chart was perfect and they fit my nails like they were custom made. My girls keep asking where I got them!',
    date: '2026-03-15',
    productBought: 'Cherry Red Coffin Nails',
    image: '',
  },
  {
    id: 'tst006',
    name: 'Sana Ijaz',
    city: 'Multan',
    rating: 5,
    comment: 'I ordered the Rose Petal Lip Gloss and the Cherry Blush Palette together. Both are halal certified which was so important to me. The gloss is SO hydrating and not sticky at all. My new daily makeup!',
    date: '2026-04-08',
    productBought: 'Rose Petal Lip Gloss + Cherry Blush Palette',
    image: '',
  },
  {
    id: 'tst007',
    name: 'Noor Aziz',
    city: 'Peshawar',
    rating: 5,
    comment: 'The scrunchie pack is the best purchase I\'ve made this year. All 5 colors are beautiful and the satin is SO soft. My hair breaks so much less now. Highly recommend to everyone!',
    date: '2026-02-22',
    productBought: 'Scrunchie Pack - Soft Girl',
    image: '',
  },
  {
    id: 'tst008',
    name: 'Rida Shah',
    city: 'Quetta',
    rating: 5,
    comment: 'Bought the Girlfriend Gift Set for my sister\'s birthday. She was absolutely over the moon. Everything was so cute and the packaging was gift-ready. Saved me so much time. 10/10 service!',
    date: '2026-03-05',
    productBought: 'Girlfriend Gift Set',
    image: '',
  },
  {
    id: 'tst009',
    name: 'Aleena Tariq',
    city: 'Sialkot',
    rating: 4,
    comment: 'The Cherry Claw Clip Set is adorable! All three clips hold really well. Only 4 stars because one of the smaller clips had a tiny scratch but customer service was amazing and offered a replacement immediately.',
    date: '2026-04-12',
    productBought: 'Cherry Claw Clip Set',
    image: '',
  },
  {
    id: 'tst010',
    name: 'Maham Khan',
    city: 'Hyderabad',
    rating: 5,
    comment: 'The Dried Rose Bouquet is absolutely gorgeous. It has been on my study desk for 3 months now and still looks perfect. The colors didn\'t fade at all. Worth every rupee!',
    date: '2026-01-30',
    productBought: 'Dried Rose Bouquet',
    image: '',
  },
  {
    id: 'tst011',
    name: 'Bushra Nawaz',
    city: 'Gujranwala',
    rating: 5,
    comment: 'The Glass Skin Serum is a game changer. My skin has been looking SO dewy and glowy since I started using it. The K-beauty formulation really works. Will definitely repurchase!',
    date: '2026-04-25',
    productBought: 'Glass Skin Serum Drops',
    image: '',
  },
  {
    id: 'tst012',
    name: 'Warda Rehman',
    city: 'Lahore',
    rating: 5,
    comment: 'CherryCore is literally the best Pakistani accessories brand. Fast delivery, beautiful packaging, amazing quality. The Y2K Star Sunglasses are so fun and I wear them everywhere. Love love love!',
    date: '2026-03-20',
    productBought: 'Y2K Star Sunglasses',
    image: '',
  },
];
